routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout' , 'Auth\LoginController@logout')->name('logout');
Route::resource('/clients','ClientsController');
Route::resource('/sponsors','SponsorsController');
Route::resource('/roles','RolesController');
Route::resource('/permissions','PermissionsController');
Route::resource('/admissions','AdmissionsController');
Route::resource('/employees','EmployeesController');
Route::resource('/users', 'UsersController');
Route::resource('/stations','StationsController');
Route::post('/get-clients-name','HomeController@getClientsName');
Route::post('/get-sponsors-name','HomeController@getSponsorsName');
Route::resource('/financials','FinancialsController');
Route::post('/get-admission-details-for-financial','HomeController@getAdmissionDetails');
Route::get('/rehab-balace','HomeController@getRehabBalance');

app/Station.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Station extends Model
{
    //
}

app/Http/Controllers/StationsController.php
<?php

namespace App\Http\Controllers;

use App\Station;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class StationsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        if (Auth::user()->can('stations.index'))
        {
            $stations = Station::all();
            return view('stations.home',compact('stations'));
        }
        abort('401');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->can('stations.create'))
        {
           return view('stations.create');
        }
        abort('401');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $addStation = new Station();
        $addStation->name = $request->name;
        $addStation->save();

        return redirect(route('stations.index'))->with('message','Station Added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (Auth::user()->can('stations.show'))
        {
            $stationDetails = Station::find($id);
            return view('stations.show',compact('stationDetails'));
        }
        abort('401');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::user()->can('stations.edit'))
        {
            $editStation = Station::find($id);
            return view('stations.edit',compact('editStation'));
        }
        abort('401');

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $updateStation = Station::find($id);
        $updateStation->name = $request->name;
        $updateStation->save();

        return redirect(route('stations.index'))->with('message','Station details updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Auth::user()->can('stations.delete'))
        {
            $deleteStation = Station::find($id);
            $deleteStation->delete();

            return redirect(route('stations.index'))->with('message','Station Deleted Successfully');
        }
        abort('401');
    }
}

resources/views/stations/create.blade.php
@extends('layouts.master')
@section('main-content')
@section('content-header')
    <h1>
        Add Station
    </h1>
    <ol class="breadcrumb">
        <li>Add a new station</li>
    </ol>
@endsection
<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-horizontal" method="POST" action="{!! route('stations.store') !!}">
            {{ csrf_field() }}
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name" class="col-md-4 control-label">Name</label>

                <div class="col-md-6">
                    <input id="name" type="text" class="form-control" name="name"
                           value="{{ old('name') }}" required
                           autofocus>
                    @if ($errors->has('name'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-6 col-md-offset-4">
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/stations/edit.blade.php
@extends('layouts.master')
@section('main-content')
@section('content-header')
    <h1>
        Edit Station
    </h1>
    <ol class="breadcrumb">
        <li>Edit a details of a station</li>
    </ol>
@endsection
<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-horizontal" method="POST" action="{!! route('stations.update',$editStation->id) !!}">
            {{ csrf_field() }}
            {!! method_field('PATCH') !!}
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name" class="col-md-4 control-label">Name</label>

                <div class="col-md-6">
                    <input id="name" type="text" class="form-control" name="name"
                           value="{{ $editStation->name }}" required
                           autofocus>
                    @if ($errors->has('name'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-6 col-md-offset-4">
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/stations/home.blade.php
@extends('layouts.master')
@section('content-header')
    <h1>
        Stations
    </h1>
    <ol class="breadcrumb">
        <li>Stations available in the system</li>
    </ol>
@endsection
@section('main-content')
    <div class="box">
        <div class="box-body">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{route('stations.create')}}">Add New</a>
            </div>
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th class="text-center">S/N</th>
                    <th>Station Name</th>
                    <th>Date Added</th>
                    <th class="text-center">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($stations as $station)
                    <tr>
                        <td class="text-center">{{ $loop->index + 1 }}</td>
                        <td>{!! $station->name !!}</td>
                        <td>{!! $station->created_at->toDateString() !!}</td>
                        <td class="text-center">
                            <a href="{{ route('stations.edit',$station->id) }}"><span class="glyphicon glyphicon-edit" style="margin-right: 8px;"></span></a>
                            <a data-toggle="modal" data-target="#modal-danger-{{$station->id}}"><span class="glyphicon glyphicon-trash"></span></a>
                            <div class="modal modal-danger fade" id="modal-danger-{{$station->id}}">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title">Delete?</h4>
                                        </div>
                                        <div class="modal-body">
                                            <p>Are you sure you want to permanently delete {!! $station->name !!}?</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal" onclick="event.preventDefault();">No</button>
                                            <button type="button" class="btn btn-outline" onclick="
                                                    document.getElementById('delete-form-{{ $station->id }}').submit();
                                                    ">Yes</button>
                                        </div>
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                                <form id="delete-form-{{ $station->id }}" method="post"
                                      action="{{ route('stations.destroy',$station->id) }}" style="display: none">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                </form>
                            </div>

                        </td>
                    </tr>
                @endforeach
                </tbody>
                <tfoot>
                <tr>
                    <th class="text-center">S/N</th>
                    <th>Station Name</th>
                    <th>Date Added</th>
                    <th class="text-center">Action</th>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection

resources/views/stations/show.blade.php
@extends('layouts.master')
@section('main-content')
@section('content-header')
    <h1>
       {!! $stationDetails->name !!}
    </h1>
    <ol class="breadcrumb">
        <li> Details of {!! $stationDetails->name !!}</li>
    </ol>
@endsection
<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-horizontal" id="delete-station" method="POST" action="{!! route('clients.destroy',$clientsDetails->id) !!}">
            {{ csrf_field() }}
            {{method_field('DELETE')}}
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name" class="col-md-4 control-label">Name</label>

                <div class="col-md-6">
                    <input id="name" type="text" class="form-control" name="name"
                           value="{{ $clientsDetails->name }}"
                           autofocus readonly>
                    @if ($errors->has('name'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-6 col-md-offset-4">
                    @can('stations.edit')
                        <a class="btn btn-warning" href="{{route('stations.edit',$stationDetails->id)}}"> Edit</a>
                    @endcan
                    @can('stations.delete')
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-danger">
                        Delete
                    </button>
                    @endcan
                </div>
            </div>
        </form>
    </div>
</div>
<div class="modal modal-danger fade" id="modal-danger">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Delete?</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to permanently delete  {!! $clientsDetails->name !!}?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal" onclick="event.preventDefault();">No</button>
                <button type="button" class="btn btn-outline" onclick="
                        document.getElementById('delete-station').submit();
                        ">Yes</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@endsection