routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout' , 'Auth\LoginController@logout')->name('logout');
Route::resource('/clients','ClientsController');
Route::resource('/sponsors','SponsorsController');
Route::resource('/roles','RolesController');
Route::resource('/permissions','PermissionsController');
Route::resource('/admissions','AdmissionsController');
Route::resource('/employees','EmployeesController');
Route::resource('/users', 'UsersController');
Route::resource('/stations','StationsController');
Route::post('/get-clients-name','HomeController@getClientsName');
Route::post('/get-sponsors-name','HomeController@getSponsorsName');
Route::resource('/financials','FinancialsController');
Route::post('/get-admission-details-for-financial','HomeController@getAdmissionDetails');
Route::get('/rehab-balace','HomeController@getRehabBalance');

app/Sponsor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sponsor extends Model
{
    public function clients()
    {
        return $this->belongsToMany('App\Client');
    }
}

app/Http/Controllers/SponsorsController.php
<?php

namespace App\Http\Controllers;

use App\Sponsor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SponsorsController extends Controller
{
    public function __construct() {
        $this->middleware(['auth']);
    }
    /**
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->can('sponsors.index'))
        {
            $sponsors = Sponsor::all();
            return view('sponsors.home',compact('sponsors'));
        }
        abort('401');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->can('sponsors.create'))
        {
            return view('sponsors.create');
        }
        abort('401');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'idnumber'=>'required|max:10|unique:sponsors',
        ]);
        $createSponsor = new Sponsor();
        $createSponsor->lastname = $request->lastname;
        $createSponsor->firstname = $request->firstname;
        $createSponsor->middlename = $request->middlename;
        $createSponsor->idnumber = $request->idnumber;
        $createSponsor->contact = $request->contact;
        $createSponsor->residence = $request->residence;
        $createSponsor->save();

        return redirect(route('sponsors.index'))->with('message','Sponsor added successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       if (Auth::user()->can('sponsors.show'))
       {
           $showSponsor = Sponsor::find($id);
           return view('sponsors.show',compact('showSponsor'));
       }
       abort('401');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::user()->can('sponsors.edit'))
        {
            $editSponsor = Sponsor::find($id);
            return view('sponsors.edit',compact('editSponsor'));
        }
        abort('401');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $updateSponsor = Sponsor::find($id);
        $updateSponsor->lastname = $request->lastname;
        $updateSponsor->firstname = $request->firstname;
        $updateSponsor->middlename = $request->middlename;
        $updateSponsor->idnumber = $request->idnumber;
        $updateSponsor->contact = $request->contact;
        $updateSponsor->residence = $request->residence;
        $updateSponsor->save();

        return redirect(route('sponsors.index'))->with('message','Sponsor details updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Auth::user()->can('sponsors.delete'))
        {
            $deleteSponsor = Sponsor::find($id);
            $deleteSponsor->delete();

            return redirect(route('sponsors.index'))->with('message','Sponsor deleted successfully');
        }
        abort('401');
    }
}

resources/views/sponsors/create.blade.php
@extends('layouts.master')
@section('main-content')
@section('content-header')
    <h1>
        Add Sponsor
    </h1>
    <ol class="breadcrumb">
        <li>Add Sponsor</li>
    </ol>
@endsection
<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-horizontal" method="POST" action="{!! route('sponsors.store') !!}">
            {{ csrf_field() }}
            <div class="form-group{{ $errors->has('lastname') ? ' has-error' : '' }}">
                <label for="lastname" class="col-md-4 control-label">Last Name</label>

                <div class="col-md-6">
                    <input id="lastname" type="text" class="form-control" name="lastname" value="{{ old('lastname') }}" required
                           autofocus>
                    @if ($errors->has('lastname'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('lastname') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('firstname') ? ' has-error' : '' }}">
                <label for="firstname" class="col-md-4 control-label">First Name</label>

                <div class="col-md-6">
                    <input id="firstname" type="text" class="form-control" name="firstname" value="{{ old('firstname') }}" required
                           autofocus>
                    @if ($errors->has('firstname'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('firstname') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('middlename') ? ' has-error' : '' }}">
                <label for="middlename" class="col-md-4 control-label">Middle Name</label>

                <div class="col-md-6">
                    <input id="middlename" type="text" class="form-control" name="middlename" value="{{ old('middlename') }}" required
                           autofocus>
                    @if ($errors->has('middlename'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('middlename') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('idnumber') ? ' has-error' : '' }}">
                <label for="idnumber" class="col-md-4 control-label">ID Number</label>

                <div class="col-md-6">
                    <input id="idnumber" type="text" class="form-control" name="idnumber" value="{{ old('idnumber') }}"
                           required>

                    @if ($errors->has('idnumber'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('idnumber') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('residence') ? ' has-error' : '' }}">
                <label for="residence" class="col-md-4 control-label">Residence</label>

                <div class="col-md-6">
                    <input id="residence" type="text" class="form-control" name="residence" value="{{ old('residence') }}"
                           required>

                    @if ($errors->has('residence'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('residence') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('contact') ? ' has-error' : '' }}">
                <label for="contact" class="col-md-4 control-label">Contact</label>

                <div class="col-md-6">
                    <input id="contact" type="text" class="form-control" name="contact" value="{{ old('contact') }}"
                           required>

                    @if ($errors->has('contact'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('contact') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6 col-md-offset-4">
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/sponsors/edit.blade.php
@extends('layouts.master')
@section('main-content')
@section('content-header')
    <h1>
        {!! $editSponsor->firstname !!} {!! $editSponsor->middlename !!} {!! $editSponsor->lastname !!}
    </h1>
    <ol class="breadcrumb">
        <li>{!! $editSponsor->firstname !!} {!! $editSponsor->middlename !!} {!! $editSponsor->lastname !!}</li>
    </ol>
@endsection
<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-horizontal" id="delete-client" method="POST" action="{!! route('sponsors.update',$editSponsor->id) !!}">
            {{ csrf_field() }}
            {{method_field('PUT')}}
            <div class="form-group{{ $errors->has('lastname') ? ' has-error' : '' }}">
                <label for="lastname" class="col-md-4 control-label">Last Name</label>
                <div class="col-md-6">
                    <input id="lastname" type="text" class="form-control" name="lastname" value="{{ $editSponsor->lastname}}" required
                           autofocus>
                    @if ($errors->has('lastname'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('lastname') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('firstname') ? ' has-error' : '' }}">
                <label for="firstname" class="col-md-4 control-label">First Name</label>

                <div class="col-md-6">
                    <input id="firstname" type="text" class="form-control" name="firstname" value="{{ $editSponsor->firstname}}" required
                           autofocus>
                    @if ($errors->has('firstname'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('firstname') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('middlename') ? ' has-error' : '' }}">
                <label for="middlename" class="col-md-4 control-label">Middle Name</label>

                <div class="col-md-6">
                    <input id="middlename" type="text" class="form-control" name="middlename" value="{{ $editSponsor->middlename}}" required
                           autofocus>
                    @if ($errors->has('middlename'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('middlename') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('idnumber') ? ' has-error' : '' }}">
                <label for="idnumber" class="col-md-4 control-label">ID Number</label>

                <div class="col-md-6">
                    <input id="idnumber" type="text" class="form-control" name="idnumber" value="{{ $editSponsor->idnumber}}"
                           required>

                    @if ($errors->has('idnumber'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('idnumber') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('residence') ? ' has-error' : '' }}">
                <label for="residence" class="col-md-4 control-label">Residence</label>

                <div class="col-md-6">
                    <input id="residence" type="text" class="form-control" name="residence" value="{{ $editSponsor->residence}}"
                           required>

                    @if ($errors->has('residence'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('residence') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('contact') ? ' has-error' : '' }}">
                <label for="contact" class="col-md-4 control-label">Contact</label>

                <div class="col-md-6">
                    <input id="contact" type="text" class="form-control" name="contact" value="{{ $editSponsor->contact}}"
                           required>

                    @if ($errors->has('contact'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('contact') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-6 col-md-offset-4">
                    <button type="submit" class="btn btn-primary">
                        Save Changes
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/sponsors/home.blade.php
@extends('layouts.master')
@section('content-header')
    <h1>
        Sponsors
    </h1>
    <ol class="breadcrumb">
        <li>Sponsors</li>
    </ol>
@endsection
@section('main-content')
    <div class="box">
        <div class="box-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th class="text-center">S/N</th>
                    <th>Name</th>
                    <th>ID Number</th>
                    <th>Contact</th>
                    <th>Residence</th>
                    <th>Date Added</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($sponsors as $sponsor)
                    <tr>
                        <td class="text-center">{{ $loop->index + 1 }}</td>
                        <td>{!! $sponsor->firstname !!} {!! $sponsor->middlename !!} {!! $sponsor->lastname !!}</td>
                        <td>{!! $sponsor->idnumber !!}</td>
                        <td>{!! $sponsor->contact !!}</td>
                        <td> {!! $sponsor->residence !!}</td>
                        <td>{!! $sponsor->created_at->toDateString() !!}</td>
                        <td><a class="btn btn-primary btn-xs"
                               href="{!! route('sponsors.show',$sponsor->id) !!}">Manage</a></td>
                    </tr>
                @endforeach
                </tbody>
                <tfoot>
                <tr>
                    <th class="text-center">S/N</th>
                    <th>Name</th>
                    <th>ID Number</th>
                    <th>Contact</th>
                    <th>Residence</th>
                    <th>Date Added</th>
                    <th>Action</th>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection

resources/views/sponsors/show.blade.php
@extends('layouts.master')
@section('main-content')
@section('content-header')
    <h1>
        {!! $showSponsor->firstname !!} {!! $showSponsor->middlename !!} {!! $showSponsor->lastname !!}
    </h1>
    <ol class="breadcrumb">
        <li>{!! $showSponsor->firstname !!} {!! $showSponsor->middlename !!} {!! $showSponsor->lastname !!}</li>
    </ol>
@endsection
<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-horizontal" id="delete-sponsor" method="POST" action="{!! route('sponsors.destroy',$showSponsor->id) !!}">
            {{ csrf_field() }}
            {{method_field('DELETE')}}
            <div class="form-group{{ $errors->has('lastname') ? ' has-error' : '' }}">
                <label for="lastname" class="col-md-4 control-label">Last Name</label>
                <div class="col-md-6">
                    <input id="lastname" type="text" class="form-control" name="lastname" value="{{ $showSponsor->lastname}}" readonly
                           autofocus>
                    @if ($errors->has('lastname'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('lastname') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('firstname') ? ' has-error' : '' }}">
                <label for="firstname" class="col-md-4 control-label">First Name</label>

                <div class="col-md-6">
                    <input id="firstname" type="text" class="form-control" name="firstname" value="{{ $showSponsor->firstname}}" readonly
                           autofocus>
                    @if ($errors->has('firstname'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('firstname') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('middlename') ? ' has-error' : '' }}">
                <label for="middlename" class="col-md-4 control-label">Middle Name</label>

                <div class="col-md-6">
                    <input id="middlename" type="text" class="form-control" name="middlename" value="{{ $showSponsor->middlename}}" readonly
                           autofocus>
                    @if ($errors->has('middlename'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('middlename') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('idnumber') ? ' has-error' : '' }}">
                <label for="idnumber" class="col-md-4 control-label">ID Number</label>

                <div class="col-md-6">
                    <input id="idnumber" type="text" class="form-control" name="idnumber" value="{{ $showSponsor->idnumber}}"
                           readonly>

                    @if ($errors->has('idnumber'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('idnumber') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('residence') ? ' has-error' : '' }}">
                <label for="residence" class="col-md-4 control-label">Residence</label>

                <div class="col-md-6">
                    <input id="residence" type="text" class="form-control" name="residence" value="{{ $showSponsor->residence}}"
                           readonly>

                    @if ($errors->has('residence'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('residence') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('contact') ? ' has-error' : '' }}">
                <label for="contact" class="col-md-4 control-label">Contact</label>

                <div class="col-md-6">
                    <input id="contact" type="text" class="form-control" name="contact" value="{{ $showSponsor->contact}}"
                           readonly>

                    @if ($errors->has('contact'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('contact') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-6 col-md-offset-4">
                    <a class="btn btn-warning" href="{{route('sponsors.edit',$showSponsor->id)}}"> Edit</a>

                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-danger">
                        Delete
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="modal modal-danger fade" id="modal-danger">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Delete?</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to permanently delete  {!! $showSponsor->firstname !!} {!! $showSponsor->middlename !!} {!! $showSponsor->lastname !!}?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal" onclick="event.preventDefault();">No</button>
                <button type="button" class="btn btn-outline" onclick="
                        event.preventDefault();
                        document.getElementById('delete-sponsor').submit();
                        ">Yes</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@endsection