routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout' , 'Auth\LoginController@logout')->name('logout');
Route::resource('/clients','ClientsController');
Route::resource('/sponsors','SponsorsController');
Route::resource('/roles','RolesController');
Route::resource('/permissions','PermissionsController');
Route::resource('/admissions','AdmissionsController');
Route::resource('/employees','EmployeesController');
Route::resource('/users', 'UsersController');
Route::resource('/stations','StationsController');
Route::post('/get-clients-name','HomeController@getClientsName');
Route::post('/get-sponsors-name','HomeController@getSponsorsName');
Route::resource('/financials','FinancialsController');
Route::post('/get-admission-details-for-financial','HomeController@getAdmissionDetails');
Route::get('/rehab-balace','HomeController@getRehabBalance');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    public function sponsors()
    {
        return $this->belongsToMany('App\Sponsor');
    }
}

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ClientsController extends Controller
{
    public function __construct() {
        $this->middleware(['auth']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->can('clients.index'))
        {
            $clients = Client::all();
            return view('clients.home',compact('clients'));
        }
        abort('401');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->can('clients.create'))
        {
            return view('clients.create');
        }
        abort('401');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $addClient = new Client();
        $addClient->admno = $request->admno;
        $addClient->lastname = $request->lastname;
        $addClient->firstname = $request->firstname;
        $addClient->middlename = $request->middlename;
        $addClient->medicalhistory = $request->medicalhistory;
        $addClient->drugofchoice = $request->drugofchoice;
        $addClient->residence = $request->residence;
        $addClient->contact = $request->contact;

        $addClient->save();

        return redirect(route('clients.index'))->with('message','Client Added Successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (Auth::user()->can('clients.show'))
        {
            $clientsDetails = Client::find($id);
            return view('clients.show',compact('clientsDetails'));
        }
        abort('401');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::user()->can('clients.edit'))
        {
            $editClient = Client::find($id);
            return view('clients.edit',compact('editClient'));
        }
        abort('401');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $updateClient = Client::find($id);
        $updateClient->admno = $request->admno;
        $updateClient->lastname = $request->lastname;
        $updateClient->firstname = $request->firstname;
        $updateClient->middlename = $request->middlename;
        $updateClient->medicalhistory = $request->medicalhistory;
        $updateClient->drugofchoice = $request->drugofchoice;
        $updateClient->residence = $request->residence;
        $updateClient->contact = $request->contact;

        $updateClient->save();

        return redirect(route('clients.index'))->with('message','Client details updated successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Auth::user()->can('clients.delete'))
        {
            $deleteClient = Client::find($id);
            $deleteClient->delete();
            return redirect(route('clients.index'))->with('message','Client deleted successfully');
        }
        abort('401');
    }
}

resources/views/clients/create.blade.php
@extends('layouts.master')
@section('main-content')
@section('content-header')
    <h1>
        Add Client
    </h1>
    <ol class="breadcrumb">
        <li>Add Client</li>
    </ol>
@endsection
<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-horizontal" method="POST" action="{!! route('clients.store') !!}">
            {{ csrf_field() }}
            <div class="form-group{{ $errors->has('admno') ? ' has-error' : '' }}">
                <label for="admno" class="col-md-4 control-label">Admission Number</label>

                <div class="col-md-6">
                    <input id="admno" type="text" class="form-control" name="admno" value="{{ old('admno') }}"
                           required
                           autofocus>
                    @if ($errors->has('admno'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('admno') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('lastname') ? ' has-error' : '' }}">
                <label for="lastname" class="col-md-4 control-label">Last Name</label>

                <div class="col-md-6">
                    <input id="lastname" type="text" class="form-control" name="lastname"
                           value="{{ old('lastname') }}" required
                           autofocus>
                    @if ($errors->has('lastname'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('lastname') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('firstname') ? ' has-error' : '' }}">
                <label for="firstname" class="col-md-4 control-label">First Name</label>

                <div class="col-md-6">
                    <input id="firstname" type="text" class="form-control" name="firstname"
                           value="{{ old('firstname') }}" required
                           autofocus>
                    @if ($errors->has('firstname'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('firstname') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('middlename') ? ' has-error' : '' }}">
                <label for="middlename" class="col-md-4 control-label">Middle Name</label>

                <div class="col-md-6">
                    <input id="middlename" type="text" class="form-control" name="middlename"
                           value="{{ old('middlename') }}" required
                           autofocus>
                    @if ($errors->has('middlename'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('middlename') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('medicalhistory') ? ' has-error' : '' }}">
                <label for="medicalhistory" class="col-md-4 control-label">Medical History</label>
                <div class="col-md-6">
                        <textarea id="medicalhistory" type="text" class="form-control" name="medicalhistory"
                                  value="{{ old('medicalhistory') }}" required
                                  autofocus></textarea>
                    @if ($errors->has('medicalhistory'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('medicalhistory') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('drugofchoice') ? ' has-error' : '' }}">
                <label for="drugofchoice" class="col-md-4 control-label">Drug of Choice</label>

                <div class="col-md-6">
                    <input id="drugofchoice" type="text" class="form-control" name="drugofchoice"
                           value="{{ old('drugofchoice') }}"
                           required>

                    @if ($errors->has('drugofchoice'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('drugofchoice') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('residence') ? ' has-error' : '' }}">
                <label for="residence" class="col-md-4 control-label">Residence</label>

                <div class="col-md-6">
                    <input id="residence" type="text" class="form-control" name="residence"
                           value="{{ old('residence') }}"
                           required>

                    @if ($errors->has('residence'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('residence') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('contact') ? ' has-error' : '' }}">
                <label for="contact" class="col-md-4 control-label">Contact</label>

                <div class="col-md-6">
                    <input id="contact" type="text" class="form-control" name="contact" value="{{ old('contact') }}"
                           required>

                    @if ($errors->has('contact'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('contact') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6 col-md-offset-4">
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/clients/edit.blade.php
@extends('layouts.master')
@section('main-content')
@section('content-header')
    <h1>
        Edit Client
    </h1>
    <ol class="breadcrumb">
        <li>{{$editClient->firstname}} {{$editClient->middlename}} {{$editClient->lastname}}</li>
    </ol>
@endsection
<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-horizontal" method="POST" action="{!! route('clients.update',$editClient->id) !!}">
            {{ csrf_field() }}
            {!! method_field('PUT') !!}
            <div class="form-group{{ $errors->has('admno') ? ' has-error' : '' }}">
                <label for="admno" class="col-md-4 control-label">Admission Number</label>

                <div class="col-md-6">
                    <input id="admno" type="text" class="form-control" name="admno" value="{!! $editClient->admno!!}"
                           required
                           autofocus>
                    @if ($errors->has('admno'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('admno') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('lastname') ? ' has-error' : '' }}">
                <label for="lastname" class="col-md-4 control-label">Last Name</label>

                <div class="col-md-6">
                    <input id="lastname" type="text" class="form-control" name="lastname"
                           value="{!! $editClient->lastname!!}" required
                           autofocus>
                    @if ($errors->has('lastname'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('lastname') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('firstname') ? ' has-error' : '' }}">
                <label for="firstname" class="col-md-4 control-label">First Name</label>

                <div class="col-md-6">
                    <input id="firstname" type="text" class="form-control" name="firstname"
                           value="{!! $editClient->firstname!!}" required
                           autofocus>
                    @if ($errors->has('firstname'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('firstname') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('middlename') ? ' has-error' : '' }}">
                <label for="middlename" class="col-md-4 control-label">Middle Name</label>

                <div class="col-md-6">
                    <input id="middlename" type="text" class="form-control" name="middlename"
                           value="{!! $editClient->middlename!!}" required
                           autofocus>
                    @if ($errors->has('middlename'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('middlename') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('medicalhistory') ? ' has-error' : '' }}">
                <label for="medicalhistory" class="col-md-4 control-label">Medical History</label>
                <div class="col-md-6">
                        <textarea id="medicalhistory" type="text" class="form-control" name="medicalhistory"
                                  required
                                  autofocus>{!! $editClient->medicalhistory!!}</textarea>
                    @if ($errors->has('medicalhistory'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('medicalhistory') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('drugofchoice') ? ' has-error' : '' }}">
                <label for="drugofchoice" class="col-md-4 control-label">Drug of Choice</label>

                <div class="col-md-6">
                    <input id="drugofchoice" type="text" class="form-control" name="drugofchoice"
                           value="{!! $editClient->drugofchoice!!}"
                           required>

                    @if ($errors->has('drugofchoice'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('drugofchoice') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('residence') ? ' has-error' : '' }}">
                <label for="residence" class="col-md-4 control-label">Residence</label>

                <div class="col-md-6">
                    <input id="residence" type="text" class="form-control" name="residence"
                           value="{!! $editClient->residence!!}"
                           required>

                    @if ($errors->has('residence'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('residence') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('contact') ? ' has-error' : '' }}">
                <label for="contact" class="col-md-4 control-label">Contact</label>

                <div class="col-md-6">
                    <input id="contact" type="text" class="form-control" name="contact" value="{!! $editClient->contact!!}"
                           required>

                    @if ($errors->has('contact'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('contact') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6 col-md-offset-4">
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/clients/home.blade.php
@extends('layouts.master')
@section('content-header')
    <h1>
        Clients
    </h1>
    <ol class="breadcrumb">
        <li>Clients</li>
    </ol>
@endsection
@section('main-content')
    <div class="box">
        <div class="box-body">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{route('clients.create')}}">Add New</a>
            </div>
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th class="text-center">S/N</th>
                    <th>Adm No</th>
                    <th>Name</th>
                    <th>Drug of Choice</th>
                    <th>Medical History</th>
                    <th>Contact</th>
                    <th>Residence</th>
                    <th>Date Added</th>
                    <th class="text-center">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($clients as $client)
                    <tr>
                        <td class="text-center">{{ $loop->index + 1 }}</td>
                        <td>{!! $client->admno !!}</td>
                        <td>{!! $client->firstname !!} {!! $client->middlename !!} {!! $client->lastname !!}</td>
                        <td>{!! $client->drugofchoice !!}</td>
                        <td>{!! $client->medicalhistory !!}</td>
                        <td>{!! $client->contact !!}</td>
                        <td> {!! $client->residence !!}</td>
                        <td>{!! $client->created_at->toDateString() !!}</td>
                        <td class="text-center">
                            <a href="{{ route('clients.edit',$client->id) }}"><span class="glyphicon glyphicon-edit" style="margin-right: 8px;"></span></a>
                            <a data-toggle="modal" data-target="#modal-danger-{{$client->id}}"><span class="glyphicon glyphicon-trash"></span></a>
                            <div class="modal modal-danger fade" id="modal-danger-{{$client->id}}">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title">Delete?</h4>
                                        </div>
                                        <div class="modal-body">
                                            <p>Are you sure you want to permanently delete {!! $client->firstname !!} {!! $client->middlename !!} {!! $client->lastname !!}?</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal" onclick="event.preventDefault();">No</button>
                                            <button type="button" class="btn btn-outline" onclick="
                                                    document.getElementById('delete-form-{{ $client->id }}').submit();
                                                    ">Yes</button>
                                        </div>
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                                <form id="delete-form-{{ $client->id }}" method="post"
                                      action="{{ route('clients.destroy',$client->id) }}" style="display: none">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                </form>
                            </div>

                        </td>
                    </tr>
                @endforeach
                </tbody>
                <tfoot>
                <tr>
                    <th class="text-center">S/N</th>
                    <th>Adm No</th>
                    <th>Name</th>
                    <th>Drug of Choice</th>
                    <th>Contact</th>
                    <th>Residence</th>
                    <th>Date Added</th>
                    <th class="text-center">Action</th>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection

resources/views/clients/show.blade.php
@extends('layouts.master')
@section('main-content')
@section('content-header')
    <h1>
       {!! $clientsDetails->firstname !!} {!! $clientsDetails->middlename !!} {!! $clientsDetails->lastname !!}
    </h1>
    <ol class="breadcrumb">
        <li>{!! $clientsDetails->firstname !!} {!! $clientsDetails->middlename !!} {!! $clientsDetails->lastname !!}</li>
    </ol>
@endsection
<div class="panel panel-default">
    <div class="panel-body">
        <form class="form-horizontal" id="delete-client" method="POST" action="{!! route('clients.destroy',$clientsDetails->id) !!}">
            {{ csrf_field() }}
            {{method_field('DELETE')}}
            <div class="form-group{{ $errors->has('admno') ? ' has-error' : '' }}">
                <label for="admno" class="col-md-4 control-label">Admission Number</label>

                <div class="col-md-6">
                    <input id="admno" type="text" class="form-control" name="admno" value="{{$clientsDetails->admno }}"
                           autofocus readonly>
                    @if ($errors->has('admno'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('admno') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('lastname') ? ' has-error' : '' }}">
                <label for="lastname" class="col-md-4 control-label">Last Name</label>

                <div class="col-md-6">
                    <input id="lastname" type="text" class="form-control" name="lastname"
                           value="{{ $clientsDetails->lastname }}"
                           autofocus readonly>
                    @if ($errors->has('lastname'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('lastname') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('firstname') ? ' has-error' : '' }}">
                <label for="firstname" class="col-md-4 control-label">First Name</label>

                <div class="col-md-6">
                    <input id="firstname" type="text" class="form-control" name="firstname"
                           value="{{$clientsDetails->firstname}}"
                           autofocus readonly>
                    @if ($errors->has('firstname'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('firstname') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('middlename') ? ' has-error' : '' }}">
                <label for="middlename" class="col-md-4 control-label">Middle Name</label>

                <div class="col-md-6">
                    <input id="middlename" type="text" class="form-control" name="middlename"
                           value="{{$clientsDetails->middlename}}"
                           autofocus readonly>
                    @if ($errors->has('middlename'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('middlename') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('medicalhistory') ? ' has-error' : '' }}">
                <label for="medicalhistory" class="col-md-4 control-label">Medical History</label>
                <div class="col-md-6">
                        <textarea id="medicalhistory" type="text" class="form-control" name="medicalhistory"
                                  autofocus readonly>{{$clientsDetails->medicalhistory}}</textarea>
                    @if ($errors->has('medicalhistory'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('medicalhistory') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('drugofchoice') ? ' has-error' : '' }}">
                <label for="drugofchoice" class="col-md-4 control-label">Drug of Choice</label>

                <div class="col-md-6">
                    <input id="drugofchoice" type="text" class="form-control" name="drugofchoice"
                           value="{{ $clientsDetails->drugofchoice }}"
                           required readonly>

                    @if ($errors->has('drugofchoice'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('drugofchoice') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('residence') ? ' has-error' : '' }}">
                <label for="residence" class="col-md-4 control-label">Residence</label>

                <div class="col-md-6">
                    <input id="residence" type="text" class="form-control" name="residence"
                           value="{{ $clientsDetails->residence }}"
                           readonly>

                    @if ($errors->has('residence'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('residence') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>
            <div class="form-group{{ $errors->has('contact') ? ' has-error' : '' }}">
                <label for="contact" class="col-md-4 control-label">Contact</label>

                <div class="col-md-6">
                    <input id="contact" type="text" class="form-control" name="contact" value="{{ $clientsDetails->contact }}"
                           required readonly>

                    @if ($errors->has('contact'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('contact') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6 col-md-offset-4">
                    @can('clients.edit')
                        <a class="btn btn-warning" href="{{route('clients.edit',$clientsDetails->id)}}"> Edit</a>
                    @endcan
                    @can('clients.delete')
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-danger">
                        Delete
                    </button>
                    @endcan
                </div>
            </div>
        </form>
    </div>
</div>
<div class="modal modal-danger fade" id="modal-danger">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Delete?</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to permanently delete  {!! $clientsDetails->firstname !!} {!! $clientsDetails->middlename !!} {!! $clientsDetails->lastname !!}?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal" onclick="event.preventDefault();">No</button>
                <button type="button" class="btn btn-outline" onclick="
                        document.getElementById('delete-client').submit();
                        ">Yes</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@endsection